### PR TITLE
Giotto-TDA 2020 Challenge

### PR DESCRIPTION
**Pull request by antonio-leitao**
Using topological data analysis to predict volcano eruption.

### CODE REVIEW

**Comment by giotto-learn** [comment]
Dear @Antonio-Leitao ,
Thank you for your PR.

The CI is not working because of missing dependencies. can you please add the following dependency at the beginning of your Jupiter notebook? 

```
import sys
!{sys.executable} -m pip install [...] tensorflow-addons
```

Hopefully the CI will pass (locally on my machine it works :) )

Finally, I would ask you to accept the CLA: it is a necessary beaureaucratical step for the company to be able to divulge the content of your notebook. It does not prevent the use of your notebooks nor its results in any other context, publication, ...

**Comment by antonio-leitao** [comment]
Thank you very much for the details. I added some images in the notebook but the html seems to be messed up when trying to see it in the repo. I hope it behaves on your side. 

Thanks,
 António. 

P.S. Theres a txt file called "Team.txt" that has the names of the participants

**Comment by giotto-learn** [comment]
No problem for the HTML rendering: locally it renders properly.

Let's wait for the CI: if it passes, it's done and you are automatically subscribed to the challenge. Otherwise we will make it work (maybe tomorrow morning) ;)

**Comment by giotto-learn** [comment]
Dear @Antonio-Leitao ,

There is a problem in your notebook: have a look [here](https://github.com/giotto-ai/gtda-challenge-2020/pull/5/checks?check_run_id=1403852827#step:5:84).

Which version of gtda are you using locally? Can you please check to be using 0.3.0 ? It is most likely a minor bug, with possibly a slight change in the output format. 

Can you please have a look?

**Comment by antonio-leitao** [comment]
Strange, I ran everything 2 times.
Let me check again

**Comment by antonio-leitao** [comment]
ok turns it might have been the gta version. Updating seems to have fixed it (i hope).

**Comment by antonio-leitao** [comment]
Apparently that wasn't what was causing the issue. 
I have rechecked and everything is up to date including gtda at version 0.3.0
It could be github not managing to fetch the data because its not local, it gets it directly from Kaggle. That would explain the error. However its impossible for me to reproduce it in my machine and if github can't get the data directly from kaggle then there's not much salvageable from the approach.
I'll keep on trying for a couple of hours we'll see.

**Comment by giotto-learn** [comment]
I'll try to run locally and tell you what happens

**Comment by antonio-leitao** [comment]
Thanks,
I just went through everything again, it has to be the integration (or lack of) between github and kaggle's API.

António Leitão

**Comment by giotto-learn** [comment]
I see this warning: do you see it as well?

Screenshot 2020-11-16 at 02 27 16

Do you have it as well? the docs for Amplitude are [here](https://giotto-ai.github.io/gtda-docs/0.3.0/modules/generated/diagrams/features/gtda.diagrams.Amplitude.html?highlight=amplitude)

**Comment by giotto-learn** [comment]
dear @Antonio-Leitao ,

After those warnings, I also got the same errors as those of the CI:

Screenshot 2020-11-16 at 02 34 20

**Comment by giotto-learn** [comment]
dear @Antonio-Leitao ,

Here is the problem: one of your aptitude is not of shape (10,2) as, I guess, you were expecting.

Screenshot 2020-11-16 at 02 39 32

The incriminated element is in position 237

**Comment by giotto-learn** [comment]
Here is a screenshot: the easiest solution would probably be to pad the vector with zeros programmatically: does it make sense to add one line of checks in the for-loop that generates`amplitude`and `entropy`? Also `entropy`suffers from the same bug.
Screenshot 2020-11-16 at 02 45 14

**Comment by giotto-learn** [comment]
Found the **source of the bug**. In the file lists you import there is also a `train_csv` file that is created automatically.

it is enough to modify your creation of the `volcano_ids` list with the following lines:

```
file_list = os.listdir('data/')
file_list.remove('train_csv')
volcano_ids = [item for item in file_list]
labels = pd.read_csv('train.csv')

```

Let's see if the whole CI passes then!

**Comment by giotto-learn** [comment]
Due to time constraints, I took the liberty to make this small modification to make the CI pass (🤞 ). I hope you don't mind!!

**Comment by giotto-learn** [comment]
Dear @Antonio-Leitao ,

You are officially part fo the challenge, as all the conditions are met! Thank you for your submission.

I will soon contact you with further instructions.

Good luck!! 😉

**Comment by antonio-leitao** [comment]
well thats very strange because i specifically say to not loop over that "train.csv" (as you can see when it creates the diagrams it skips the last entry "for volcano in volcano_ids[:-1]" Anyway I'm very happy its fixed. Sorry for the trouble.

**Pull request merged**
