### PR TITLE
A topological search engine for retrieving relevant documents. 

### PR DESCRIPTION
**Pull request by Filco306**
Hello! This is my contribution to the `gtda-challenge 2020`! This was a fun competition to participate in, and I hope you like my contribution! :D

### CODE REVIEW

**Comment by Filco306** [comment]
Woohoo!!

**Comment by Filco306** [comment]
For the interested person, I might add that the last version was supposed to work, but I used an older version of gtda, leading me to have the exact same problem as I had in [#518](https://github.com/giotto-ai/giotto-tda/issues/518). Either way, it passed now!

**Comment by giotto-learn** [comment]
Dear @Filco306 ,

Thank you for your PR. You are officially subscribed to the challenge, as all the conditions are met!

Thank you for your participation: I will soon share further instructions.

**Comment by Filco306** [comment]
Thank you very much @giotto-learn ! :D

**Pull request merged**
