### PR TITLE
Topological disease type prediction - submission to gtda challenge by G. Petri and A. Leitao 

### PR DESCRIPTION
**Pull request by lordgrilo**

### CODE REVIEW

**Comment by lordgrilo** [comment]
I'm not sure what are the steps required to fix the error above, since it seems to be crashing because it doesn't recognise the name of my local jupyter kernel. Please let me know what steps I should take to comply with github's requirements and yours.

**Comment by giotto-learn** [comment]
Dear @lordgrilo ,

Thank you very much for your PR. The CI is not yet passing: hopefully we will fix it quickly.

Can you please try to open your notebook with a text editor -- whichever you prefer, e.g. atom or vim -- and look for the following metadata:
```
  "kernelspec": {
   "display_name": "pyenv3.8",
   "language": "python",
   "name": "pyenv3.8"
  },
```

Please substitute the above with:

```
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },

```

Finally, I would ask you to approve the CLA, as it is a necessary bureaucratic step to allow the company to divulge your work and publish it on the social media. It will not prevent you in any way to use your ideas and code you submit in other challenges, publications,...

**Comment by lordgrilo** [comment]
Hey guys, 

I'm lost because now Github is complaining that it doens't like gensim.
Screenshot 2020-11-16 at 00 44 41
but --as per instructions-- the notebook starts with this:
Screenshot 2020-11-16 at 00 48 02
I'm not sure what to do to fix this. 
Gensim is a pretty standard package to my knowledge and pip installs it without problems locally.

**Comment by giotto-learn** [comment]
checking now...

**Comment by Filco306** [comment]
`gensim` worked for me; that is strange. You can see my PR #4 and see what might differ. 

How nice by the way with another one using `gtda` with word vectors! :D Will be interesting to see your contribution!

**Comment by giotto-learn** [comment]
Dear @lordgrilo ,

Can you please:
1. add a new **initial cell** to your code with the following lines:
```
# reload modules before executing user code
%load_ext autoreload
# reload all modules every time before executing the Python code
%autoreload 2
```

2. please copy the following installation cell (also the *new lines*) and substitute it with the current one:

```
import sys

!{sys.executable} -m pip install gensim numpy scipy tsfresh matplotlib

```
3. You will notice that `glob` is missing. Can you please check which version of glob you are using? Appartenly on pypi, you can find [these ones](https://pypi.org/search/?q=glob). If it is just the [python `glob`](https://docs.python.org/3/library/glob.html), there is no need to pip install it.


Hopefully the bug is because the kernel is not refreshed when the new packages are installed. Let's hope it works this time!

**Comment by giotto-learn** [comment]
Btw, in my local version -- with the changes above -- I managed to make it run past the installation steps. Hopefully it will run till the end and so will the CI!

**Comment by giotto-learn** [comment]
I confirm that locally it works properly till the end. Can you please add the *autoreload* and remove *glob* from the list of dependencies?

> Dear @lordgrilo ,
> 
> Can you please:
> 
> 1. add a new **initial cell** to your code with the following lines:
> 
> ```
> # reload modules before executing user code
> %load_ext autoreload
> # reload all modules every time before executing the Python code
> %autoreload 2
> ```
> 
> 1. please copy the following installation cell (also the _new lines_) and substitute it with the current one:
> 
> ```
> import sys
> 
> !{sys.executable} -m pip install gensim numpy scipy tsfresh matplotlib
> ```
> 
> 1. You will notice that `glob` is missing. If it is just the [python `glob`](https://docs.python.org/3/library/glob.html), there is no need to pip install it.
> 
> Hopefully the bug is because the kernel is not refreshed when the new packages are installed. Let's hope it works this time!

**Comment by giotto-learn** [comment]
Once you do these short modifications, I am positive the CI will work and if it does, you will be automatically and officially subscribed to the challenge. Otherwise we'll fix the next bug! ;) 

And please don't forget the CLA.

**Comment by giotto-learn** [comment]
@lordgrilo Perfect, the CI passed!!

The final step is to accept the CLA, which you can do by clicking on the badge (top of the page):

Screenshot 2020-11-16 at 10 41 46

**Comment by giotto-learn** [comment]
The CLA is signed, as per the attached img:

Screenshot 2020-11-16 at 11 11 15

So @lordgrilo ,

You are officially subscribed to the gtda-challenge-2020. Thank you for your submission. I will contact you very soon with further instructions.

Good luck!

**Pull request merged**
